# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ecc6ce001bd61fa1ea8932a611f0a2674234971e00416410c76745b27ddac74268195c79bf2b8851d0e1aa287a3a0ee59acd5f940d022a3f8768b7f30db37a

test:
  secret_key_base: 619c3e803f5993c11431c61922081a9dbcddc29ecb7a60e6c8b511b5c6d119d90ff1f611da9fb34fdaa76498585e3e3d65083e0ec761e3c6f700040adfc78101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
